#フォーマットバージョン2
Vagrant.configure("2") do |config|
  config.vm.box = "my-study-mail.box"
  config.vm.network "public_network", ip: "192.168.255.110"

  config.vm.provider "virtualbox" do |v|
    v.name = "my-study-mail-2"
  end

end
